### ISSUE TITLE
Dev Setup improvements

### ISSUE THREAD

**Issue by enjikaka** [thomascullen/voicebox#12]
I followed the steps in under "Dev Setup". When I pressed `ALT + S` the box did not appear. I was getting `Renderer process started` in the console though. Then it realised grunt is watching for file changes, so I opened the listening.js and saved it without doing changes. Then the `ALT + S` command worked.

Would be nice with a little note under "Dev Setup" that tells you that you need to save a file in the components directory before using the command.

**Comment by thomascullen** [comment]
Thanks for this. I will update the Gruntfile to compile on startup as well which should fix this issue!
